'use client'
import { useEffect, useState } from 'react';
import { Box, Button, Checkbox, Flex, FormControl, FormLabel, Heading, Input, SimpleGrid, Spinner, Stack, Text, useToast } from '@chakra-ui/react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { meetingReminderSettingsService, MeetingReminderSettings, MeetingType } from '@/services/meetingReminderSettingsService';
const labels: Record<MeetingType, string> = { CONTENT: 'Conteúdo', PRACTICAL: 'Prática', ASSESSMENT: 'Avaliação' };
export default function SettingsPage() {
 const toast = useToast(); const [data, setData] = useState<MeetingReminderSettings | null>(null); const [saving, setSaving] = useState(false);
 useEffect(() => { meetingReminderSettingsService.get().then(setData).catch(() => toast({ status: 'error', title: 'Não foi possível carregar as configurações' })); }, [toast]);
 if (!data) return <DashboardLayout><Spinner /></DashboardLayout>;
 const toggle = (type: MeetingType) => setData({ ...data, enabledMeetingTypes: data.enabledMeetingTypes.includes(type) ? data.enabledMeetingTypes.filter(v => v !== type) : [...data.enabledMeetingTypes, type] });
 const save = async () => { if (!data.enabledMeetingTypes.length) return toast({ status: 'warning', title: 'Selecione ao menos um tipo de encontro' }); setSaving(true); try { setData(await meetingReminderSettingsService.update(data)); toast({ status: 'success', title: 'Configurações salvas' }); } catch { toast({ status: 'error', title: 'Não foi possível salvar' }); } finally { setSaving(false); } };
 return <DashboardLayout><Flex justify="space-between" align="center" mb={6}><Box><Heading size="lg" color="gray.700">Configurações gerais</Heading><Text color="gray.500" mt={1}>Controle os avisos automáticos de encontros e o cronograma diário dos professores.</Text></Box><Button colorScheme="orange" onClick={save} isLoading={saving}>Salvar configurações</Button></Flex><Box bg="white" borderRadius="lg" boxShadow="sm" p={{ base: 5, md: 6 }}><SimpleGrid columns={{ base: 1, lg: 3 }} spacing={8}><FormControl><FormLabel>Antecedência do aviso ao aluno (horas)</FormLabel><Input type="number" min={1} max={168} value={data.reminderLeadHours} onChange={e => setData({ ...data, reminderLeadHours: Number(e.target.value) })} /></FormControl><FormControl><FormLabel>Tipos de encontro que receberão aviso</FormLabel><Stack spacing={3}>{(Object.keys(labels) as MeetingType[]).map(type => <Checkbox key={type} isChecked={data.enabledMeetingTypes.includes(type)} onChange={() => toggle(type)}>{labels[type]}</Checkbox>)}</Stack></FormControl><FormControl><FormLabel>Horário do cronograma diário do professor</FormLabel><Input type="time" value={data.teacherDailyScheduleTime.slice(0, 5)} onChange={e => setData({ ...data, teacherDailyScheduleTime: e.target.value })} /><Text fontSize="sm" color="gray.500" mt={1}>O e-mail é enviado no fuso horário cadastrado do professor.</Text></FormControl></SimpleGrid></Box></DashboardLayout>;
}
